# Generated by Django 4.2.7 on 2023-11-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_customer_user'),
    ]

    operations = [
    ]
