# Generated by Django 4.2.7 on 2023-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_customer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
