# Generated by Django 4.2.7 on 2023-12-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='managerid',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
